### ISSUE TITLE
Roadmap for SimulAI

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#87]
#### Short term development (fundamental steps) :

- [ ] Coverage for more than 95 % of the source code.
- [ ] Complete documentation for all the classes and methods. 
- [ ] Automating the execution of sanity tests and coverage. 
- [ ] Examples in notebooks for all the cases seen in the directory examples. 

#####  Medium term Development 

- [ ] Complete scalability tests for Data Distributed Parallelism (DDP) and Full-Sharded Data Parallelism (FSDP), using SimulAI models. 
- [ ] Pipelines execution optimized via JIT (TorchScript, maybe PyPy)

**Comment by TarikKaanKoc** [comment]
I will start on saturday 🦅🦅🦅
